//
//  Constants.swift
//  CatFacts
//
//  Created by Pae on 1/17/16.
//  Copyright © 2016 Pae. All rights reserved.
//

import Foundation

extension UIColor {
    
    convenience init(hex: Int) {
        
        let components = (
            R: CGFloat((hex >> 16) & 0xff) / 255,
            G: CGFloat((hex >> 08) & 0xff) / 255,
            B: CGFloat((hex >> 00) & 0xff) / 255
        )
        
        self.init(red: components.R, green: components.G, blue: components.B, alpha: 1)
    }
    
}

let AppStoreLink = "https://itunes.apple.com/app/id1074493881?mt=8"

let kPrimaryColor = UIColor(hex: 0x3F9DD9)
let kDeviceIsIPAD = UIDevice.current.userInterfaceIdiom == .pad

let kUUIDSignupPwd = "UUIDSignup"
let kUUIDSignedUpKey = "UUIDSignedUp"

let kChatServerId = "Server"
let kChatServerName = "Cat Facts"
let kChatContactId = "Contact"

let kCreditPurchaseItems =
    [["name":"Credit Pack +10", "desc":"You could increase the credits by 10 for $0.99", "productId":"com.mjm.catfacts.creditpack10", "increaseCredit":10, "price":"$0.99"],
    ["name":"Credit Pack +20", "desc":"You could increase the credits by 20 for $1.99", "productId":"com.mjm.catfacts.creditpack20", "increaseCredit":20, "price":"$1.99"],
    ["name":"Credit Pack +30", "desc":"You could increase the credits by 30 for $2.99", "productId":"com.mjm.catfacts.creditpack30", "increaseCredit":30, "price":"$2.99"],
    ["name":"Credit Pack +40", "desc":"You could increase the credits by 40 for $3.99", "productId":"com.mjm.catfacts.creditpack40", "increaseCredit":40, "price":"$3.99"],
    ["name":"Credit Pack +50", "desc":"You could increase the credits by 50 for $4.99", "productId":"com.mjm.catfacts.creditpack50", "increaseCredit":50, "price":"$4.99"],
    ["name":"Credit Pack +100", "desc":"You could increase the credits by 100 for $9.99", "productId":"com.mjm.catfacts.creditpack100", "increaseCredit":100, "price":"$9.99"],
    ["name":"Credit Pack +200", "desc":"You could increase the credits by 200 for $19.99", "productId":"com.mjm.catfacts.creditpack200", "increaseCredit":200, "price":"$19.99"],
    ["name":"Credit Pack +300", "desc":"You could increase the credits by 300 for $29.99", "productId":"com.mjm.catfacts.creditpack300", "increaseCredit":300, "price":"$29.99"]]

let kContactStatusSendingColor = UIColor(red: 93.0/255, green: 190.0/255, blue: 113.0/255, alpha: 1.0)
let kContactStatusPausedColor = UIColor(red: 190.0/255, green: 166.0/255, blue: 93.0/255, alpha: 1.0)
let kContactStatusBlockedColor = UIColor(red: 190.0/255, green: 93.0/255, blue: 93.0/255, alpha: 1.0)

let kContactStatusColorArray = [kContactStatusSendingColor, kContactStatusPausedColor, kContactStatusBlockedColor]
let kContactStatusTextArray = ["Sending", "Paused", "Blocked"]


let kFlagValues = [
    "+1",
    "+1",
    "+44",
    "+61",
    "+65",
    "+93",
    "+355",
    "+213",
    "+376",
    "+244",
    "+54",
    "+374",
    "+297",
    "+43",
    "+994",
    "+973",
    "+880",
    "+375",
    "+32",
    "+501",
    "+229",
    "+975",
    "+591",
    "+387",
    "+267",
    "+55",
    "+673",
    "+359",
    "+226",
    "+95",
    "+257",
    "+855",
    "+237",
    "+1",
    "+238",
    "+236",
    "+235",
    "+56",
    "+86",
    "+61",
    "+61",
    "+57",
    "+269",
    "+242",
    "+243",
    "+682",
    "+506",
    "+385",
    "+53",
    "+357",
    "+420",
    "+45",
    "+253",
    "+670",
    "+593",
    "+20",
    "+503",
    "+240",
    "+291",
    "+372",
    "+251",
    "+500",
    "+298",
    "+679",
    "+358",
    "+33",
    "+689",
    "+241",
    "+220",
    "+995",
    "+233",
    "+350",
    "+30",
    "+299",
    "+502",
    "+224",
    "+245",
    "+592",
    "+509",
    "+504",
    "+852",
    "+36",
    "+91",
    "+62",
    "+98",
    "+964",
    "+353",
    "+44",
    "+972",
    "+39",
    "+225",
    "+81",
    "+962",
    "+7",
    "+254",
    "+686",
    "+49",
    "+965",
    "+996",
    "+856",
    "+371",
    "+961",
    "+266",
    "+231",
    "+218",
    "+423",
    "+370",
    "+352",
    "+853",
    "+389",
    "+261",
    "+265",
    "+60",
    "+960",
    "+223",
    "+356",
    "+692",
    "+222",
    "+230",
    "+262",
    "+52",
    "+691",
    "+373",
    "+377",
    "+976",
    "+382",
    "+212",
    "+258",
    "+264",
    "+674",
    "+977",
    "+31",
    "+599",
    "+687",
    "+64",
    "+505",
    "+227",
    "+234",
    "+683",
    "+850",
    "+47",
    "+968",
    "+92",
    "+680",
    "+507",
    "+675",
    "+595",
    "+51",
    "+63",
    "+870",
    "+48",
    "+351",
    "+1",
    "+974",
    "+40",
    "+7",
    "+250",
    "+590",
    "+685",
    "+378",
    "+239",
    "+966",
    "+221",
    "+381",
    "+248",
    "+232",
    "+421",
    "+386",
    "+677",
    "+252",
    "+27",
    "+82",
    "+34",
    "+94",
    "+290",
    "+508",
    "+249",
    "+597",
    "+268",
    "+46",
    "+41",
    "+963",
    "+886",
    "+992",
    "+255",
    "+66",
    "+228",
    "+690",
    "+676",
    "+216",
    "+90",
    "+993",
    "+688",
    "+971",
    "+256",
    "+380",
    "+598",
    "+998",
    "+678",
    "+39",
    "+58",
    "+84",
    "+681",
    "+967",
    "+260",
    "+263"
]

let kFlagSuffix = [
     "us",
     "ca",
     "gb",
     "au",
     "sg",
     "af",
     "al",
     "dz",
     "ad",
     "ao",
     "ar",
     "am",
     "aw",
     "at",
     "az",
     "bh",
     "bd",
     "by",
     "be",
     "bz",
     "bj",
     "bt",
     "bo",
     "ba",
     "bw",
     "br",
     "bn",
     "bg",
     "bf",
     "mm",
     "bi",
     "kh",
     "cm",
     "cv",
     "cf",
     "td",
     "cl",
     "cn",
     "cx",
     "cc",
     "co",
     "km",
     "cg",
     "cd",
     "ck",
     "cr",
     "hr",
     "cu",
     "cy",
     "cz",
     "dk",
     "dj",
     "tl",
     "ec",
     "eg",
     "sv",
     "gq",
     "er",
     "ee",
     "et",
     "fk",
     "fo",
     "fj",
     "fi",
     "fr",
     "pf",
     "ga",
     "gm",
     "ge",
     "gh",
     "gi",
     "gr",
     "gl",
     "gt",
     "gn",
     "gw",
     "gy",
     "ht",
     "hn",
     "hk",
     "hu",
     "in",
     "id",
     "ir",
     "iq",
     "ie",
     "im",
     "il",
     "it",
     "ci",
     "jp",
     "jo",
     "kz",
     "ke",
     "ki",
     "de",
     "kw",
     "kg",
     "la",
     "lv",
     "lb",
     "ls",
     "lr",
     "ly",
     "li",
     "lt",
     "lu",
     "mo",
     "mk",
     "mg",
     "mw",
     "my",
     "mv",
     "ml",
     "mt",
     "mh",
     "mr",
     "mu",
     "yt",
     "mx",
     "fm",
     "md",
     "mc",
     "mn",
     "me",
     "ma",
     "mz",
     "na",
     "nr",
     "np",
     "nl",
     "an",
     "nc",
     "nz",
     "ni",
     "ne",
     "ng",
     "nu",
     "kp",
     "no",
     "om",
     "pk",
     "pw",
     "pa",
     "pg",
     "py",
     "pe",
     "ph",
     "pn",
     "pl",
     "pt",
     "pr",
     "qa",
     "ro",
     "ru",
     "rw",
     "bl",
     "ws",
     "sm",
     "st",
     "sa",
     "sn",
     "rs",
     "sc",
     "sl",
     "sk",
     "si",
     "sb",
     "so",
     "za",
     "kr",
     "es",
     "lk",
     "sh",
     "pm",
     "sd",
     "sr",
     "sz",
     "se",
     "ch",
     "sy",
     "tw",
     "tj",
     "tz",
     "th",
     "tg",
     "tk",
     "to",
     "tn",
     "tr",
     "tm",
     "tv",
     "ae",
     "ug",
     "ua",
     "uy",
     "uz",
     "vu",
     "va",
     "ve",
     "vn",
     "wf",
     "ye",
     "zm",
     "zw"
]


let kCountryName = [
     "United States of America",
     "Canada",
     "United Kingdom",
     "Australia",
     "Singapore",
     "Afghanistan",
     "Albania",
     "Algeria",
     "Andorra",
     "Angola",
     "Argentina",
     "Armenia",
     "Aruba",
     "Austria",
     "Azerbaijan",
     "Bahrain",
     "Bangladesh",
     "Belarus",
     "Belgium",
     "Belize",
     "Benin",
     "Bhutan",
     "Bolivia",
     "Bosnia and Herzegovina",
     "Botswana",
     "Brazil",
     "Brunei Darussalam",
     "Bulgaria",
     "Burkina Faso",
     "Myanmar",
     "Burundi",
     "Cambodia",
     "Cameroon",
     "Cabo Verde",
     "Central African Republic",
     "Chad",
     "Chile",
     "China",
     "Christmas Island",
     "Cocos (Keeling) Islands",
     "Colombia",
     "Comoros",
     "Congo",
     "Congo (the Democratic Republic)",
     "Cook Islands",
     "Costa Rica",
     "Croatia",
     "Cuba",
     "Cyprus",
     "Czechia",
     "Denmark",
     "Djibouti",
     "Timor-Leste",
     "Ecuador",
     "Egypt",
     "El Salvador",
     "Equatorial Guinea",
     "Eritrea",
     "Estonia",
     "Ethiopia",
     "Falkland Islands [Malvinas]",
     "Faroe Islands",
     "Fiji",
     "Finland",
     "France",
     "French Polynesia",
     "Gabon",
     "Gambia (the)",
     "Georgia",
     "Ghana",
     "Gibraltar",
     "Greece",
     "Greenland",
     "Guatemala",
     "Guinea",
     "Guinea-Bissau",
     "Guyana",
     "Haiti",
     "Honduras",
     "Hong Kong",
     "Hungary",
     "India",
     "Indonesia",
     "Iran",
     "Iraq",
     "Ireland",
     "Isle of Man",
     "Israel",
     "Italy",
     "Côte d'Ivoire",
     "Japan",
     "Jordan",
     "Kazakhstan",
     "Kenya",
     "Kiribati",
     "Germany",
     "Kuwait",
     "Kyrgyzstan",
     "Lao People's Democratic Republic",
     "Latvia",
     "Lebanon",
     "Lesotho",
     "Liberia",
     "Libya",
     "Liechtenstein",
     "Lithuania",
     "Luxembourg",
     "Macao",
     "Republic of North Macedonia",
     "Madagascar",
     "Malawi",
     "Malaysia",
     "Maldives",
     "Mali",
     "Malta",
     "Marshall Islands",
     "Mauritania",
     "Mauritius",
     "Mayotte",
     "Mexico",
     "Micronesia",
     "Moldova",
     "Monaco",
     "Mongolia",
     "Montenegro",
     "Morocco",
     "Mozambique",
     "Namibia",
     "Nauru",
     "Nepal",
     "Netherlands (the)",
     "Netherlands Antilles",
     "New Caledonia",
     "New Zealand",
     "Nicaragua",
     "Niger (the)",
     "Nigeria",
     "Niue",
     "North Korea",
     "Norway",
     "Oman",
     "Pakistan",
     "Palau",
     "Panama",
     "Papua New Guinea",
     "Paraguay",
     "Peru",
     "Philippines (the)",
     "Pitcairn",
     "Poland",
     "Portugal",
     "Puerto Rico",
     "Qatar",
     "Romania",
     "Russian Federation (the)",
     "Rwanda",
     "Saint Barthélemy",
     "Samoa",
     "San Marino",
     "Sao Tome and Principe",
     "Saudi Arabia",
     "Senegal",
     "Serbia",
     "Seychelles",
     "Sierra Leone",
     "Slovakia",
     "Slovenia",
     "Solomon Islands",
     "Somalia",
     "South Africa",
     "South Korea",
     "Spain",
     "Sri Lanka",
     "Saint Helena, Ascension and Tristan da Cunha",
     "Saint Pierre and Miquelon",
     "Sudan",
     "Suriname",
     "Eswatini",
     "Sweden",
     "Switzerland",
     "Syrian Arab Republic",
     "Taiwan",
     "Tajikistan",
     "Tanzania, United Republic of",
     "Thailand",
     "Togo",
     "Tokelau",
     "Tonga",
     "Tunisia",
     "Turkey",
     "Turkmenistan",
     "Tuvalu",
     "United Arab Emirates",
     "Uganda",
     "Ukraine",
     "Uruguay",
     "Uzbekistan",
     "Vanuatu",
     "Holy See",
     "Venezuela",
     "Viet Nam",
     "Wallis and Futuna",
     "Yemen",
     "Zambia",
     "Zimbabwe"
]
